### ISSUE TITLE
🚧Fix issue with parsing PR template

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/KDAdmin#15]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix an issue with parsing the PR template when creating a new PR.
When creating a new PR for the VelaptorDocs project, the config was setup to use a new PR template in the organizational repo named _**feature-to-prod-template.md**_.

The error thrown in the CLI when creating the PR is shown below.
```bash
➜ kdadmin config run -n="feature"
        Running the configuration feature. . .
 ? Prev Feature Issue Number: » 5
 ? Enter a description of the branch. » update-project-readme
 ? Please choose a branch. » master

[git] Switched to branch 'master'
[git] Switched to branch 'feature/5-update-project-readme'
[git] remote:
[git] remote: Create a pull request for 'feature/5-update-project-readme' on GitHub by visiting:
[git] remote:      https://github.com/KinsonDigital/VelaptorDocs/pull/new/feature/5-update-project-readme
[git] remote:
[git] remote: GitHub found 6 vulnerabilities on KinsonDigital/VelaptorDocs's default branch (4 high, 2 moderate). To find out more, visit:
[git] remote:      https://github.com/KinsonDigital/VelaptorDocs/security/dependabot     
[git] remote:
[git] To https://github.com/KinsonDigital/VelaptorDocs.git
[git]  * [new branch]      feature/5-update-project-readme -> feature/5-update-project-readmeerror: Uncaught (in promise) Error: Parse error on "<" (error) at [6, 21]
                        throw new Error(ChalkColor.error(error));
                              ^
    at GitHubClient.getResponseData (https://raw.githubusercontent.com/KinsonDigital/KDAdmin/v1.0.0-preview.1/src/services/GitHubClient.ts:832:10)
    at async GitHubClient.createPR (https://raw.githubusercontent.com/KinsonDigital/KDAdmin/v1.0.0-preview.1/src/services/GitHubClient.ts:691:46)
    at async PRService.createPR (https://raw.githubusercontent.com/KinsonDigital/KDAdmin/v1.0.0-preview.1/src/services/PRService.ts:144:37)
```

The best way to test this would be to create a test issue to use its number.  Use postman and the template content to see if the issue can be reproduced.

### Acceptance Criteria

- [ ] Issue fixed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
